<!--
/**
 * Copyright © Wirecard Brasil. All rights reserved.
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See COPYING.txt for license details.
 */
-->
<?php if ($block->getMethodCode() == 'moip_magento2_boleto'): ?>
    <p>
        <?= /* @noEscape */ __('The barcode of your ticket bank is:') ?> 
        <div class="field osc-input-group">
            <div class="control _with-tooltip">
                <input type="text"
                    id="copyTarget"
                    value="<?= /* @noEscape */ $block->getInfo('boleto_line_code'); ?>"
                    class="input-text"/> 
                <div class="field-tooltip toggle">
                    <button id="copyButton">
                        <?= /* @noEscape */ __('Copy') ?> 
                    </button>
                </div>
            </div>
        </div>
        
    </p>
    <p>
        <a href="<?= /* @noEscape */ $block->getInfo('boleto_print_href'); ?>"
            target="_blank"
            class="action primary continue">
            <?= /* @noEscape */ __('Print your ticket bank') ?> 
        </a>
    </p>
    <script type="text/javascript">
        document.getElementById("copyButton").addEventListener("click", function() {
            copyToClipboard(document.getElementById("copyTarget"));
        });

        function copyToClipboard(elem) {
            var targetId = "_hiddenCopyText_";
            var isInput = elem.tagName === "INPUT" || elem.tagName === "TEXTAREA";
            var origSelectionStart, origSelectionEnd;
            if (isInput) {
                // can just use the original source element for the selection and copy
                target = elem;
                origSelectionStart = elem.selectionStart;
                origSelectionEnd = elem.selectionEnd;
            } else {
                // must use a temporary form element for the selection and copy
                target = document.getElementById(targetId);
                if (!target) {
                    var target = document.createElement("textarea");
                    target.style.position = "absolute";
                    target.style.left = "-9999px";
                    target.style.top = "0";
                    target.id = targetId;
                    document.body.appendChild(target);
                }
                target.textContent = elem.textContent;
            }
            // select the content
            var currentFocus = document.activeElement;
            target.focus();
            target.setSelectionRange(0, target.value.length);
            
            // copy the selection
            var succeed;
            try {
                  succeed = document.execCommand("copy");
            } catch(e) {
                succeed = false;
            }
            // restore original focus
            if (currentFocus && typeof currentFocus.focus === "function") {
                currentFocus.focus();
            }
            
            if (isInput) {
                // restore prior selection
                elem.setSelectionRange(origSelectionStart, origSelectionEnd);
            } else {
                // clear temporary content
                target.textContent = "";
            }
            return succeed;
    }
    </script>
<?php endif; ?>