<!--
/**
 * Copyright © Moip by PagSeguro. All rights reserved.
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See COPYING.txt for license details.
 */
-->
<?php if ($block->getMethodCode() == 'moip_magento2_boleto'): ?>
    <div class="moip-info-boleto">
        <?= /* @noEscape */ __('The barcode of your ticket bank is:') ?> 
        <div class="field osc-input-group">
            <div class="control _with-tooltip">
                <input type="text"
                    id="copyTarget"
                    value="<?= /* @noEscape */ $block->getInfo('boleto_line_code'); ?>"
                    class="input-text"/> 
                <div class="field-tooltip toggle">
                    <button id="copyButton">
                        <?= /* @noEscape */ __('Copy') ?> 
                    </button>
                </div>
            </div>
        </div>
        
    </div>
    <div class="moip-info-boleto">
        <a href="<?= /* @noEscape */ $block->getInfo('boleto_print_href'); ?>"
            target="_blank"
            class="action primary continue">
            <?= /* @noEscape */ __('Print your ticket bank') ?> 
        </a>
    </div>
<?php endif; ?>
