<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$brand = $block->getBrand();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <dt class="title"><?= /* @noEscape */ $title ?></dt>
    <?php if ($brand):?>
        <dd class="content">
            <table class="data table">
                    <tr>
                        <th scope="row"><?= __('Installments')?></th>
                        <td>
                            <?= $block->getInstallments(); ?>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row"><?= __('Brand')?></th>
                        <td>
                            <?= $block->getBrand(); ?>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row"><?= __('Full Name')?></th>
                        <td>
                            <?= $block->getOwner(); ?>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row"><?= __('Credit Card Number')?></th>
                        <td>
                            <?= $block->getLastNumber(); ?>
                        </td>
                    </tr>
            </table>
        </dd>
    <?php endif;?>
    
</dl>
<?= $block->getChildHtml() ?>
