<!--
/**
 * Copyright © Moip by PagSeguro. All rights reserved.
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See COPYING.txt for license details.
 */
-->
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>" >
    <div class="admin__field">
        <label class="admin__field-label"><span><?= $block->escapeHtml(__('Due')) ?></span></label>
        <div class="admin__field-control checkmo-mailing-address">
            <?= /* @noEscape */ nl2br($block->escapeHtml($block->getExpiration())) ?>
        </div>
    </div>
    <div class="admin__field">
        <label class="admin__field-label"><span><?= $block->escapeHtml(__('Instruction')) ?></span></label>
        <div class="admin__field-control checkmo-mailing-address">
            <?= /* @noEscape */ nl2br($block->escapeHtml($block->getInstruction())) ?>
        </div>
    </div>
</fieldset>

<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    "display:none",
    'fieldset#payment_form_' . $block->escapeJs($block->getMethodCode())
) ?>
