<?php
/**
 * Copyright © Moip by PagSeguro. All rights reserved.
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Adminhtml\Transparent\Form $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
$ccInstallment = $block->getInfoData('cc_installment');
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>">
    <input type="hidden"
        id="<?= /* @noEscape */ $code ?>_key_public"
        value="<?= /* @noEscape */ $block->getKeyPublic() ?>"/>
    <input type="hidden" 
        id="<?= /* @noEscape */ $code ?>_cc_hash"
        name="payment[cc_hash]"
        value="<?= /* @noEscape */ $block->getInfoData('cc_hash') ?>"/>
    

    <?php if ($block->getTaxDocumentCapture()): ?>
        <div class="field-text required admin__field _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_holder_tax_document">
                <span><?= $block->escapeHtml(__('Credit Card Holder Tax Document')) ?></span>
            </label>
            <div class="admin__field-control">
                <input type="text" title="<?= $block->escapeHtml(__('Credit Card Holder Tax Document')) ?>"
                       class="required-entry admin__control-text"
                       id="<?= /* @noEscape */ $code ?>_cc_holder_tax_document"
                       name="payment[cc_holder_tax_document]"
                       value="<?= /* @noEscape */ $block->getInfoData('cc_holder_tax_document') ?>"/>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->getPhoneCapture()): ?>
        <div class="field-text required admin__field _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_holder_phone">
                <span><?= $block->escapeHtml(__('Credit Card Holder Phone')) ?></span>
            </label>
            <div class="admin__field-control">
                <input type="text" title="<?= $block->escapeHtml(__('Credit Card Holder Phone')) ?>"
                       class="required-entry admin__control-text"
                       id="<?= /* @noEscape */ $code ?>_cc_holder_phone"
                       name="payment[cc_holder_phone]"
                       value="<?= /* @noEscape */ $block->getInfoData('cc_holder_phone') ?>"/>
                <div class="admin__field-note">
                    <span><?= /* @noEscape */ __('Format: (99)99999-9999') ?></span>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->getBirthDateCapture()): ?>
        <div class="field-text required admin__field _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_holder_birth_date">
                <span><?= $block->escapeHtml(__('Credit Card Holder Birth Date')) ?></span>
            </label>
            <div class="admin__field-control">
                <input type="text" title="<?= $block->escapeHtml(__('Credit Card Holder Birth Date')) ?>"
                       class="required-entry admin__control-text"
                       id="<?= /* @noEscape */ $code ?>_cc_holder_birth_date"
                       name="payment[cc_holder_birth_date]"
                       value="<?= /* @noEscape */ $block->getInfoData('cc_holder_birth_date') ?>"/>
                <div class="admin__field-note">
                    <span><?= /* @noEscape */  __('Format: 31/12/1985') ?></span>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <div class="field-text required admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_cid">
            <span><?= $block->escapeHtml(__('Credit Card Holder Full Name')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" title="<?= $block->escapeHtml(__('Credit Card Holder Full Name')) ?>"
                   class="required-entry admin__control-text"
                   id="<?= /* @noEscape */ $code ?>_cc_holder_fullname"
                   name="payment[cc_holder_fullname]"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_holder_fullname') ?>"/>
        </div>
    </div>
    <div class="field-type admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_type">
            <span><?= $block->escapeHtml(__('Credit Card Type')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_cc_type" name="payment[cc_type]"
                    class="required-entry validate-cc-type-select admin__control-select">
                <option value=""></option>
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <option value="<?= $block->escapeHtml($typeCode) ?>"
                            <?php if ($typeCode == $ccType): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($typeName) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_number">
            <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?= /* @noEscape */ $code ?>_cc_number" name="payment[cc_number]"
                   title="<?= $block->escapeHtml(__('Credit Card Number')) ?>"
                   class="admin__control-text validate-cc-number"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_number') ?>"/>
        </div>
    </div>
    <div class="field-date admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_expiration">
            <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_expiration"
                    class="admin__control-select admin__control-select-month validate-cc-exp required-entry">
                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                    <option value="<?= $block->escapeHtml($k) ?>"
                            <?php if ($k == $ccExpMonth): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select id="<?= /* @noEscape */ $code ?>_expiration_yr" 
                    class="admin__control-select admin__control-select-year required-entry">
                <?php foreach ($block->getCcYears() as $k => $v): ?>
                    <option value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>"
                            <?php if ($k == $ccExpYear): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <?php if ($block->hasVerification()): ?>
        <div class="field-number required admin__field _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_cid">
                <span><?= $block->escapeHtml(__('Card Verification Number')) ?></span>
            </label>
            <div class="admin__field-control">
                <input type="text" title="<?= $block->escapeHtml(__('Card Verification Number')) ?>"
                       class="required-entry validate-cc-cvn admin__control-cvn admin__control-text"
                       id="<?= /* @noEscape */ $code ?>_cc_cid"
                       value="<?= /* @noEscape */ $block->getInfoData('cc_cid') ?>"/>
            </div>
        </div>
    <?php endif; ?>
    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_expiration">
            <span><?= $block->escapeHtml(__('Select Instalmment')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_cc_installments" name="payment[cc_installments]"
                        class="admin__control-select required-entry">
                <?php foreach ($block->getSelectInstallments() as $k => $v): ?>
                    <option value="<?= $block->escapeHtml($k) ?>"
                            <?php if ($k == $ccInstallment): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</fieldset>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    "display:none",
    'fieldset#payment_form_' . /* @noEscape */ $code
) ?>
<?php $scriptString = <<<script
    
    require(["Magento_Sales/order/create/form"], function () {
        order.addExcludedPaymentMethod('{$code}');
    });
    require(["Moip_Magento2/js/hash"], function () {
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>