<?php if ($block->canRefundBoleto()): ?>
<section class="admin__page-section" id="bank-details-for-refund">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Bank details for refund')); ?></span>
    </div>
    <div class="admin__page-section-content form-data-moip">
        <div class="admin__field  field-refund-boleto">
            <div class="admin__field-label">
                <label for="moip_magento2_boleto_holder_fullname" class="admin__field-label">
                    <span><?= $block->escapeHtml(__('Owner of the account')); ?></span>
                </label>
            </div>
            <div class="admin__field-control control _with-tooltip">
                <?php // phpcs:ignore Generic.Files.LineLength ?>
                <input type="text" class="input-text admin__control-text required-entry" name="creditmemo[<?= $block->escapeHtml($block->getNameInputHolderName()) ?>]" id="moip_magento2_boleto_holder_fullname" value="">
                <div class="admin__field-tooltip">
                    <div data-bind="<?= /* @noEscape */ $block->getTooltipConfig('fullname') ?>" class="hidden">
                        <?= $block->escapeHtml(__('Name of the account holder.')); ?>
                    </div>
                    <div class="tooltip" data-tooltip-trigger="moip_magento2_tooltip_fullname">
                        <span class="help"><span></span></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin__field  field-refund-boleto">
            <div class="admin__field-label">
                <label for="moip_magento2_boleto_holder_document" class="admin__field-label">
                    <span><?= $block->escapeHtml(__('Owner tax document')); ?></span>
                </label>
            </div>
            <div class="admin__field-control control _with-tooltip">
                <?php // phpcs:ignore Generic.Files.LineLength ?>
                <input type="text" class="input-text admin__control-text required-entry validate-length minimum-length-11 maximum-length-14" name="creditmemo[<?= $block->escapeHtml($block->getNameInputHolderDocument()) ?>]" id="moip_magento2_boleto_holder_document" value="">
                <div class="admin__field-tooltip">
                    <div data-bind="<?= /* @noEscape */ $block->getTooltipConfig('document') ?>" class="hidden">
                        <?= $block->escapeHtml(__('Tax document of the holder.')); ?>
                    </div>
                    <div class="tooltip" data-tooltip-trigger="moip_magento2_tooltip_document">
                        <span class="help"><span></span></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin__field  field-refund-boleto">
            <div class="admin__field-label">
                <label for="moip_magento2_boleto_bank_number" class="admin__field-label">
                    <span><?= $block->escapeHtml(__('Bank Number')); ?></span>
                </label>
            </div>
            <div class="admin__field-control control _with-tooltip">
                <?php // phpcs:ignore Generic.Files.LineLength ?>
                <input type="text" class="input-text admin__control-text required-entry validate-not-negative-number" name="creditmemo[<?= $block->escapeHtml($block->getNameInputBankNumber()) ?>]" id="moip_magento2_boleto_bank_number" value="">
                <div class="admin__field-tooltip">
                    <div data-bind="<?= /* @noEscape */ $block->getTooltipConfig('bank_number') ?>" class="hidden">
                        <?php // phpcs:ignore Generic.Files.LineLength ?>
                        <?= $block->escapeHtml(__('See bank number <a href="%1" target="_blank">here</a>', 'https://docs.moip.com.br/reference#bancos')); ?>
                    </div>
                    <div class="tooltip" data-tooltip-trigger="moip_magento2_tooltip_bank_number">
                        <span class="help"><span></span></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin__field-control-two-field">
             <div class="admin__field  field-refund-boleto agency-number">
                <div class="admin__field-label">
                    <label for="moip_magento2_boleto_agency_number" class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Agency Number')); ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <?php // phpcs:ignore Generic.Files.LineLength ?>
                    <input type="text" class="input-text admin__control-text required-entry validate-not-negative-number" name="creditmemo[<?= $block->escapeHtml($block->getNameInputAgencyNumber()) ?>]" id="moip_magento2_boleto_agency_number" value="">
                </div>
            </div>
            <div class="admin__field  field-refund-boleto agency-check-number">
                <div class="admin__field-label">
                    <label for="moip_magento2_boleto_agency_check_number" class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Agency Check Number')); ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <?php // phpcs:ignore Generic.Files.LineLength ?>
                    <input type="text" class="input-text admin__control-text validate-not-negative-number" name="creditmemo[<?= $block->escapeHtml($block->getNameInputAgencyCheck()) ?>]" id="moip_magento2_boleto_agency_check_number" value="">
                </div>
            </div>
        </div>
        <div class="admin__field-control-two-field">
            <div class="admin__field  field-refund-boleto account-number">
                <div class="admin__field-label">
                    <label for="moip_magento2_boleto_account_number" class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Account Number')); ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <?php // phpcs:ignore Generic.Files.LineLength ?>
                    <input type="text" class="input-text admin__control-text required-entry validate-not-negative-number" name="creditmemo[<?= $block->escapeHtml($block->getNameInputAccountNumber()) ?>]" id="moip_magento2_boleto_account_number" value="">
                </div>
            </div>
            <div class="admin__field  field-refund-boleto account-check-number">
                <div class="admin__field-label">
                    <label for="moip_magento2_boleto_account_check_number" class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Account Check Number')); ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <?php // phpcs:ignore Generic.Files.LineLength ?>
                    <input type="text" class="input-text admin__control-text validate-not-negative-number" name="creditmemo[<?= $block->escapeHtml($block->getNameInputAccountCheck()) ?>]" id="moip_magento2_boleto_account_check_number" value="">
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>