<?php if($block->canRefundBoleto()): ?>
<section class="admin__page-section" id="bank-details-for-refund">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Bank details for refund'); ?></span>
    </div>
    <div class="admin__page-section-content form-data-moip">
        <div class="admin__field  field-refund-boleto">
            <div class="admin__field-label">
                <label for="moip_magento2_boleto_holder_fullname" class="admin__field-label">
                    <span><?= $block->escapeHtml(__('Owner of the account')); ?></span>
                </label>
            </div>
            <div class="admin__field-control control _with-tooltip">
                <input type="text" class="input-text admin__control-text required-entry" name="creditmemo[<?= \Moip\Magento2\Block\Adminhtml\Sales\Creditmemo::HOLDER_FULLNAME ?>]" id="moip_magento2_boleto_holder_fullname" value="<?= $block->getBankNumber(); ?>">
                <div class="admin__field-tooltip">
                    <div data-bind="<?= $block->getTooltipConfig('fullname') ?>" class="hidden">
                        <?= __('Name of the account holder.'); ?>
                    </div>
                    <div class="tooltip" data-tooltip-trigger="moip_magento2_tooltip_fullname">
                        <span class="help"><span></span></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin__field  field-refund-boleto">
            <div class="admin__field-label">
                <label for="moip_magento2_boleto_holder_document" class="admin__field-label">
                    <span><?= $block->escapeHtml(__('Owner tax document')); ?></span>
                </label>
            </div>
            <div class="admin__field-control control _with-tooltip">
                <input type="text" class="input-text admin__control-text required-entry validate-length minimum-length-11 maximum-length-14" name="creditmemo[<?= \Moip\Magento2\Block\Adminhtml\Sales\Creditmemo::HOLDER_DOCUMENT_NUMBER ?>]" id="moip_magento2_boleto_holder_document" value="<?= $block->getBankNumber(); ?>">
                <div class="admin__field-tooltip">
                    <div data-bind="<?= $block->getTooltipConfig('document') ?>" class="hidden">
                        <?= __('Tax document of the holder.'); ?>
                    </div>
                    <div class="tooltip" data-tooltip-trigger="moip_magento2_tooltip_document">
                        <span class="help"><span></span></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin__field  field-refund-boleto">
            <div class="admin__field-label">
                <label for="moip_magento2_boleto_bank_number" class="admin__field-label">
                    <span><?= $block->escapeHtml(__('Bank Number')); ?></span>
                </label>
            </div>
            <div class="admin__field-control control _with-tooltip">
                <input type="text" class="input-text admin__control-text required-entry validate-not-negative-number" name="creditmemo[<?= \Moip\Magento2\Block\Adminhtml\Sales\Creditmemo::BANK_NUMBER ?>]" id="moip_magento2_boleto_bank_number" value="<?= $block->getBankNumber(); ?>">
                <div class="admin__field-tooltip">
                    <div data-bind="<?= $block->getTooltipConfig('bank_number') ?>" class="hidden">
                        <?= __('See bank number <a href="%1" target="_blank">here</a>', 'https://docs.moip.com.br/reference#bancos'); ?>
                    </div>
                    <div class="tooltip" data-tooltip-trigger="moip_magento2_tooltip_bank_number">
                        <span class="help"><span></span></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="admin__field-control-two-field">
             <div class="admin__field  field-refund-boleto agency-number">
                <div class="admin__field-label">
                    <label for="moip_magento2_boleto_agency_number" class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Agency Number')); ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <input type="text" class="input-text admin__control-text required-entry validate-not-negative-number" name="creditmemo[<?= \Moip\Magento2\Block\Adminhtml\Sales\Creditmemo::AGENCY_NUMBER ?>]" id="moip_magento2_boleto_agency_number" value="<?= $block->getBankNumber(); ?>">
                </div>
            </div>
            <div class="admin__field  field-refund-boleto agency-check-number">
                <div class="admin__field-label">
                    <label for="moip_magento2_boleto_agency_check_number" class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Agency Check Number')); ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <input type="text" class="input-text admin__control-text validate-not-negative-number" name="creditmemo[<?= \Moip\Magento2\Block\Adminhtml\Sales\Creditmemo::AGENCY_CHECK_NUMBER ?>]" id="moip_magento2_boleto_agency_check_number" value="<?= $block->getBankNumber(); ?>">
                </div>
            </div>
        </div>
        <div class="admin__field-control-two-field">
            <div class="admin__field  field-refund-boleto account-number">
                <div class="admin__field-label">
                    <label for="moip_magento2_boleto_account_number" class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Account Number')); ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <input type="text" class="input-text admin__control-text required-entry validate-not-negative-number" name="creditmemo[<?= \Moip\Magento2\Block\Adminhtml\Sales\Creditmemo::ACCOUNT_NUMBER ?>]" id="moip_magento2_boleto_account_number" value="<?= $block->getBankNumber(); ?>">
                </div>
            </div>
            <div class="admin__field  field-refund-boleto account-check-number">
                <div class="admin__field-label">
                    <label for="moip_magento2_boleto_account_check_number" class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Account Check Number')); ?></span>
                    </label>
                </div>
                <div class="admin__field-control control">
                    <input type="text" class="input-text admin__control-text validate-not-negative-number" name="creditmemo[<?= \Moip\Magento2\Block\Adminhtml\Sales\Creditmemo::ACCOUNT_CHECK_NUMBER ?>]" id="moip_magento2_boleto_account_check_number" value="<?= $block->getBankNumber(); ?>">
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>